[INCLUDE: watertemp_display.ini] ;append the custom dial bit from here

[BASIC]
OPEN_WHEELER=0
DIESEL_ENGINE=0

[SHADOWED_WHEELS]
OPACITY=0
EXTRA_AMBIENT_BRIGHTNESS=0

[SHADOWED_TYRES]
OPACITY=0
EXTRA_AMBIENT_BRIGHTNESS=0

[ANALOG_INDICATOR_0]
INPUT=TIME_HOURS				; any of supported inputs
NAME=ARROW_HOUR					; name of mesh to move
UPPER_BOUND=12					; maximum input value for arrow to move with
LOWER_BOUND=0					; minimum input value
START=0							; offset for starting point, degrees
RANGE=360						; full range of arrow to move to at the upper bound, degrees
G_FACTOR=0.1,0,0				; adds a bit of needle offset bound to G-forces for those axis

[ANALOG_INDICATOR_1]
INPUT=TIME_MINUTES				; any of supported inputs
NAME=ARROW_MINUTE			; name of mesh to move
UPPER_BOUND=60					; maximum input value for arrow to move with
LOWER_BOUND=0					; minimum input value
START=0							; offset for starting point, degrees
RANGE=360						; full range of arrow to move to at the upper bound, degrees
G_FACTOR=0.1,0,0				; adds a bit of needle offset bound to G-forces for those axis

[ANALOG_INDICATOR_2]
INPUT=OIL_PRESSURE				; any of supported inputs
NAME=ARROW_OILPRES				; name of mesh to move
LOWER_BOUND=0					; minimum input value
UPPER_BOUND=6.00				; maximum input value for arrow to move with
LUT=(|0=-30|6=30|)				; offset for starting point, degrees
RANGE=60						; full range of arrow to move to at the upper bound, degrees
SPEED_LAG=0.2					; lag for speed, adding inertia of movement

[ANALOG_INDICATOR_3]
INPUT=SPEED						; any of supported inputs
NAME=ARROW_AMMETER				; name of mesh to move
LOWER_BOUND=0.0					; minimum input value
UPPER_BOUND=240.0				; maximum input value for arrow to move with
LUT=(|0=-20|1=0|240=20|)		; offset for starting point, degrees
RANGE=40						; full range of arrow to move to at the upper bound, degrees
SPEED_LAG=0.2					; lag for speed, adding inertia of movement

[EMISSIVE_EXTRA_A_0]
NAME = dash_bulbs				; mesh name of the one you need to illuminate
COLOR = 25,25,25
LAG = 0.2
SIMULATE_HEATING=0.3
LOCATION = NONE
CAST_LIGHT = 1

[PARTICLES_FX_EXHAUST_0]
POSITION = 0.345,0.21,-2.58

[PARTICLES_FX_EXHAUST_1]
POSITION = 0.345,0.21,-2.58

[PARTICLES_FX_EXHAUST_0, PARTICLES_FX_EXHAUST_1]
SPAWN_OFFSET=0.1
DIRECTION=0,0.01,-5
SPREAD=0.2
COLOR=0.75, 0.8, 1
;GROW=1
LIFE=0.5, 1
SPEED=0.4, 0.9
INTENSITY=0.2, 0.4
TEMPERATURE_THRESHOLD=0
SPEED_THRESHOLD=15, 240

[SCRIPT_...]
SCRIPT = extra_visual_effects.lua
SKIP_FRAMES = 0
ACTIVE_FOR_NEAREST=4
ACTIVE_FOR_UNFOCUSED=1

[SCRIPT_...]
SCRIPT = chattyjeff.lua
SKIP_FRAMES = 0
ACTIVE_FOR_UNFOCUSED=0

[TYRES_FX]
DAMAGE_FLAT_SPOT_DEBUG=0      ; set it to 1 to get damaged tyres from the start
DAMAGE_GRAIN_DEBUG=0          ; set it to 1 to get damaged tyres from the start

DAMAGE_FLAT_SPOT_GAIN=0.5    ; multiplier for increasing flat spot
DAMAGE_FLAT_SPOT_FADE=0.1     ; how much of flat spot (which is in 0 1 range) will be gone after 1 km driven
DAMAGE_GRAIN_GAIN=10.0        ; multiplier for increasing grain
DAMAGE_WIDTH_K=1.1	      ; decrease to make damage more narrow and vise versa
DAMAGE_OFFSET_K=0.0         ; horizontal offset for visible damage; increase to move it closer to the car

DAMAGE_SPEC_MULT=1.5          ; by how much ksSpecular should be multiplied for fully damaged areas
DAMAGE_SPEC_EXP_MULT=0.5      ; by how much ksSpecularEXP should be multiplied for fully damaged areas
DAMAGE_REFL_MULT=5.3          ; by how much fresnelMaxLevel should be multiplied for fully damaged areas
DAMAGE_OCCLUSION_MULT=-1.2     ; how much of occlusion to substract from fully damaged areas
DAMAGE_NORMALS_MULT=1.4       ; normals multiplier for fully damaged areas

DIRT_GRASS_DEBUG=0
DIRT_ACCUMULATION=1000
DIRT_FADE=100
DIRT_WIDTH_K=1.6

[EXTRA_SWITCHES]
SWITCH_A = "Engine Starter"
SWITCH_A_FLAGS = HOLD_MODE
SWITCH_B = "Start custom repairs"
SWITCH_B_FLAGS = HOLD_MODE
SWITCH_C = "Back to Track (online only)"
SWITCH_C_FLAGS = HOLD_MODE
SWITCH_D = "Enable/Disable supercharger (if available)"
SWITCH_D_FLAGS = HOLD_MODE
SWITCH_E = "Adjust radiator shutters (close)"
SWITCH_E_FLAGS = HOLD_MODE
SWITCH_F = "Adjust radiator shutters (open)"
SWITCH_F_FLAGS = HOLD_MODE

;parts for PSG (preselector gearbox) - uncomment and adjust if PSG is in use - also need the soundfile from the extension\sfx sub-folder. see the 48 Talbot Lago
;[SCRIPT_...]
;SCRIPT = psg.lua
;SKIP_FRAMES = 0
;ACTIVE_FOR_UNFOCUSED=0

;[ANIMATION_...]
;INPUT = CPHYS_SCRIPT_50
;FILE = SHIFT.ksanim
;TIME = 0.3

;additional helper script for electricity stuff
;[SCRIPT_...]
;SCRIPT = electricity_ext.lua
;SKIP_FRAMES = 0
;ACTIVE_FOR_UNFOCUSED=1
